# Contains dictionaries for language translations

# Defines current language (0: German, 1: English)
current_language = 0

german = {
    "window" : "Client application",
    "iHeader" : "Anleitung",
    "i1" : "1. Verbinden Sie PC und HoloLens mit demselben Netzwerk",
    "i2" : "2. Auf der HoloLens: Verbinden Sie sich mit folgender IP-Adresse",
    "language" : "Deutsch",
    "exit" : "Beenden",
    "confirmHeader" : ["Beenden", "Verbindung"],
    "confirmTxt" : ["Applikation beenden?", "Verbindung mit HoloLens trennen?"],
    "confirmYes" : "Ja",
    "confirmNo" : "Nein",
    "statusHeader" : "Verbindungsstatus",
    "statusInfo" : ["Nicht verbunden", "Verbunden"],
    "modeHeader" : "Modus:",
    "infoHeader" : "Meldungen",
    "authHeader" : "Authoring",
    "visPv" : "HoloLens Stream in separatem Fenster anzeigen",
    "textHeader" : "Textanweisung:",
    "gridHeader" : "Videoanweisung (Gitterbild):", 
    "analysisHeader" : "Analyse",
    "actionLabel" : "Aktion:",
    "actionFrameLabel" : "Key Frame(s):",
    "handsLabel" : "Benutze Haende:",
    "rotDirectionLabel" : "Rotationsrichtung:",
    "genTextLabel" : "Generierter Text:",
    "responseTimeLabel" : "Antwortzeit [s]:",
    "textInstruction" : "Textanweisung:",
}

english = {
    "window" : "Client Applikation",
    "iHeader" : "Instructions",
    "i1" : "1. Connect PC and HoloLens to the same network",
    "i2" : "2. On the HoloLens: Connect to the following ip address",
    "language" : "English",
    "exit" : "Quit",
    "confirmHeader" : ["Quit", "Diconnect"],
    "confirmTxt" : ["Quit application?", "Disconnect from HoloLens?"],
    "confirmYes" : "Yes",
    "confirmNo" : "No",
    "statusHeader" : "Connection State",
    "statusInfo" : ["Not connected", "Connected"],
    "modeHeader" : "Mode:",
    "infoHeader" : "Notifications",
    "authHeader" : "Authoring",
    "visPv" : "Show HoloLens stream in separate window",
    "textHeader" : "Text instruction:",
    "gridHeader" : "Video instruction (grid):",
    "analysisHeader" : "Analysis",
    "actionLabel" : "Action",
    "actionFrameLabel" : "Key Frame(s):",
    "handsLabel" : "Used hand(s):",
    "rotDirectionLabel" : "Rotation direction:",
    "genTextLabel" : "Generated text:",
    "responseTimeLabel" : "Response time [s]:",
    "textInstruction" : "Textual instruction:",
}